name: First GitHub action workflow setup
on:
  workflow_dispatch: 
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: say hello to everyone
        run: |
          echo "Hello, Suraj Rane!"
          echo "You have Successfully Created Workflow for this"
          uname
          date
